name: CI

on:
  push:
    branches: ["master"]

jobs:
  android-build:
    name: Android Dev Build
    runs-on: self-hosted
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch 5 commits Info
        run: git log -5 --oneline > gitlog.txt
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Set version name variable
        id: set_version
        run: |
          versionNumber=$(( ${{ github.run_number }} - 67 ))
          echo "versionName=0.5.${versionNumber}" >> $GITHUB_OUTPUT
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm install --force
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: "Create env file"
        run: |
          touch .env
      - name: Log env file to gradle.properties
        run: cat android/gradle.properties
      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{github.run_number}}
          versionName: ${{ steps.set_version.outputs.versionName }}
      - run: |
          cd android
          ./gradlew clean
      - name: Build Android App
        run: npm run build-release-android
